### PR TITLE
Custom Blue owl client request

### PR DESCRIPTION
**Pull request by JanvanZetten**

### CODE REVIEW

**Comment by JanvanZetten** [comment]
unnaturalowlwithwingcolormask
unnaturalowlwithbluemask

what about one of these?

**Comment by JanvanZetten** [comment]
Or maybe something like...
unnaturalowlbigmask

**Comment by JanvanZetten** [comment]
Here it is in with a blue mask
unnaturalowlbigbluemask

**Comment by JanvanZetten** [comment]
The first edition for easy comparison
unnaturalowl

**Comment by JanvanZetten** [comment]
Which one do you all like the best?

**Review by asbamse — APPROVED** [review]
Nice work

**Comment by Applemelon** [comment]
Nice owl

**Pull request merged**
